package com.kilowats.enuns;

public enum FormaPagamento {
	DINHEIRO,
	CARTAO_DEBITO,
	CARTAO_CREDITO,
	CARTAO_CREDITO_2X,
	CARTAO_CREDITO_3X,
	CARTAO_CREDITO_4X,
	CARTAO_CREDITO_5X,
	CARTAO_CREDITO_6X,
	CARTAO_CREDITO_7X,
	CARTAO_CREDITO_8X,
	CARTAO_CREDITO_9X,
	CARTAO_CREDITO_10X,
	CHEQUE_AVISTA,
	CHEQUE_APRAZO,
	BOLETO,
	OUTRO;
}
