package com.kilowats.enuns;

public enum SituacaoTributariaIcms {
	TRIBUTADA_SIMPLES_NACIONAL_PERMISSAO_CREDITO(101, "101 – TRIBUTADA PELO SIMPLES NACIONAL COM PERMISSÃO DE  CRÉDITO"),
	TRIBUTADA_SIMPLES_NACIONAL_SEM_PERMISSAO_CREDITO(102, "102 – TRIBUTADA PELO SIMPLES NACIONAL SEM PERMISSÃO DE CRÉDITO"),
	ISENCAO_ICMS_SIMPLES_NACIONAL_FAIXA_RECEITA_BRUTA(103, "103 – ISENÇÃO DO ICMS NO SIMPLES NACIONAL PARA A FAIXA DE RECEITA BRUTA"),
	TRIBUTADA_SIMPLES_NACIONAL_PERMISSAO_CREDITO_COBRANCA_ICMS_SUBSTITUICAO_TRIBUTARIA(201, "201 – TRIBUTADA PELO SIMPLES NACIONAL COM PERMISSÃO DE CRÉDITO E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA"),
	TRIBUTADA_SIMPLES_NACIONAL_SEM_PERMISSAO_CREDITO_COBRANCA_ICMS_SUBSTITUICAO_TRIBUTARIA(202, "202 – TRIBUTADA PELO SIMPLES NACIONAL SEM PERMISSÃO DE CRÉDITO E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA"),
	ISENCAO_ICMS_SIMPLES_NACIONAL_FAIXA_RECEITA_BRUTA_COBRANCA_ICMS_SUBSTITUICAO_TRIBUTARIA(203, "203 – ISENÇÃO DO ICMS NO SIMPLES NACIONAL PARA A FAIXA DE RECEITA BRUTA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA"),
	IMUNE(300, "IMUNE"),
	NAO_TRIBUTADA_SIMPLES_NACIONAL(400, "400 - NÃO TRIBUTADA NO SIMPLES NACIONAL"),
	ICMS_COBRADO_ANTERIORMENTE_SUBSTITUICAO_TRIBUTARIA_ANTECIPACAO(500, "500 – ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTARIA OU POR ANTECIPAÇÃO"),
	OUTROS(900 ,"OUTROS");
	
	private int codIcms;
	private String descricaoIcms;
	
	private SituacaoTributariaIcms(int codIcms, String descricaoIcms) {
		this.codIcms = codIcms;
		this.descricaoIcms = descricaoIcms;
	}

	public int getCodIcms() {
		return codIcms;
	}

	public void setCodIcms(int codIcms) {
		this.codIcms = codIcms;
	}

	public String getDescricaoRegime() {
		return descricaoIcms;
	}

	public void setDescricaoRegime(String descricaoRegime) {
		this.descricaoIcms = descricaoRegime;
	}
	
}
